name: Build and Upload

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

permissions:
  contents: write

jobs:

  # build-debug and build-release are the exact same except for one keyword, which is the cmake_build_type
  # there is probably a feature to reuse these but i either cant find it or its a bigger pain in the ass to set up
  # thanks for making your documentation super clear and easy to use github

  build-debug:  
    runs-on: ubuntu-latest
    container: xingrz/rpi-pico-builder:latest
    steps:
    - uses: actions/checkout@v3
      name: Clone Phobri repo

    - name: Clone Pico SDK
      uses: suisei-cn/actions-download-file@v1
      id: pico-sdk
      with:
        url: https://codeload.github.com/raspberrypi/pico-sdk/tar.gz/refs/tags/1.5.1
        target: assets

    - name: Clone TinyUSB 
      uses: suisei-cn/actions-download-file@v1
      id: tinyusb
      with:
        url: https://codeload.github.com/hathach/tinyusb/tar.gz/refs/tags/0.15.0
        target: assets

    - name: Untar Pico SDK
      run: |
        tar xvf assets/${{ steps.pico-sdk.outputs.filename }} --transform 's/pico-sdk-1.5.1//' -C $PICO_SDK_PATH
        tar xvf assets/${{ steps.tinyusb.outputs.filename }} --transform 's/tinyusb-0.15.0//' -C $PICO_SDK_PATH/lib/tinyusb

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=DEBUG
  
    - name: Build
      # Build your program with the given configuration
      run: cmake --build build

    - name: Upload Debug UF2
      uses: actions/upload-artifact@v3
      with:
        name: debug_uf2
        path: build/Phobri64.uf2
        if-no-files-found: error

  build-release:  
    runs-on: ubuntu-latest
    container: xingrz/rpi-pico-builder:latest
    steps:
    - uses: actions/checkout@v3
      name: Clone Phobri repo

    - name: Clone Pico SDK
      uses: suisei-cn/actions-download-file@v1
      id: pico-sdk
      with:
        url: https://codeload.github.com/raspberrypi/pico-sdk/tar.gz/refs/tags/1.5.1
        target: assets

    - name: Clone TinyUSB 
      uses: suisei-cn/actions-download-file@v1
      id: tinyusb
      with:
        url: https://codeload.github.com/hathach/tinyusb/tar.gz/refs/tags/0.15.0
        target: assets

    - name: Untar Pico SDK
      run: |
        tar xvf assets/${{ steps.pico-sdk.outputs.filename }} --transform 's/pico-sdk-1.5.1//' -C $PICO_SDK_PATH
        tar xvf assets/${{ steps.tinyusb.outputs.filename }} --transform 's/tinyusb-0.15.0//' -C $PICO_SDK_PATH/lib/tinyusb

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=RELEASE

    - name: Build
      # Build your program with the given configuration
      run: cmake --build build

    - name: Upload Release UF2
      uses: actions/upload-artifact@v3
      with:
        name: release_uf2
        path: build/Phobri64.uf2
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-debug
      - build-release
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        name: Clone Phobri repo

      - uses: actions/download-artifact@v3
        name: Download UF2s

      - name: Move around files
        run: |
          mv debug_uf2/Phobri64.uf2 ./Phobri64_${{ github.ref_name }}_debug.uf2
          mv release_uf2/Phobri64.uf2 ./Phobri64_${{ github.ref_name }}_release.uf2

      - name: Push to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              Phobri64_${{ github.ref_name }}_debug.uf2
              Phobri64_${{ github.ref_name }}_release.uf2